language: ruby

before_script:
  - curl https://raw.githubusercontent.com/Arthaey/spark_pr/bar/spark_pr.rb -o spark_pr.rb

script:
  - ruby create_travis_build_history_badge.rb
  - ruby upload_travis_build_history_badge.rb
